config/routes.rb
Rails.application.routes.draw do

  get 'manyusers/index'

  get 'manyusers/show'

  get 'manyusers/edit'

  get 'manyusers/update'

  get 'manyusers/delete'

  get 'users/index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/delete'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  post 'access/login'
  post 'access/attempt_login'
  get 'access/logout'


resources :subjects do
  member do
    get :delete
  end
end

  resources :pages do
  member do
    get :delete
  end
end

resources :sections do
  member do
    get :delete
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id         :integer          not null, primary key
#  username   :string(50)
#  first_name :string(50)
#  last_name  :string(50)
#  email      :string           default(""), not null
#  password   :string(50)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class AdminUser < ApplicationRecord
   has_secure_password
   has_and_belongs_to_many :pages
   has_many :section_edits
   has_many :sections, :through => :section_edits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  subject_id :integer
#  name       :string
#  permalink  :string
#  position   :integer
#  visible    :boolean          default("false")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Page < ApplicationRecord
    belongs_to :subject
    has_many :sections
    has_and_belongs_to_many :admin_users
end

app/models/section.rb
# == Schema Information
#
# Table name: sections
#
#  id           :integer          not null, primary key
#  page_id      :integer
#  name         :string
#  position     :integer
#  visible      :boolean          default("false")
#  content_type :string
#  content      :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Section < ApplicationRecord
    belongs_to :page
    has_many :section_edits
    has_many :admin_users, :through => :section_edits
end

app/models/section_edit.rb
# == Schema Information
#
# Table name: section_edits
#
#  id            :integer          not null, primary key
#  admin_user_id :integer
#  section_id    :integer
#  summary       :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class SectionEdit < ApplicationRecord
    belongs_to :admin_user
    belongs_to :section
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id         :integer          not null, primary key
#  name       :string
#  position   :integer
#  visible    :boolean          default("false")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subject < ApplicationRecord
    has_many :pages
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def menu
  end
  def login
  end
  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(:username => params[:username]).first
      if found_user
        authorize_user = found_user.authenticate(params[:password])
      end
    end
    
    if authorize_user 
      sessions[:user_id] = authorize_user.id
      redirect_to(admin_path)
    else
      render('login')
    end
  end 

  def logout
    sessions[:user_id] = nil
    redirect_to(access_login_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/manyusers_controller.rb
class ManyusersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

layout 'admin'
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])

  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if  @page.update_attributes(page_params)
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end


  def delete
    @page = Page.find(params[:id])

  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to(pages_path)
  end

  def new
    @page = Page.new
  end

  def create
    # Intanciate new Object


    @page = Page.new(page_params)
    
    # Save the Object
    if @page.save 
      redirect_to(pages_path)

    else
      render('new')
    end
  end
  private
    def page_params
      params.require(:page).permit(:name, :position, :visible, :permalink, :subject_id)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
layout 'admin'
# Create
  def new
    @section = Section.new
  end
  def create
    @section = Section.new(section_params)

    if @section.save 
      redirect_to(sections_path)
    else
      render('new')
    end
  end
# Read
  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end
# Update
  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])

    if @section.update_attributes(section_params)
      redirect_to(section_path(@section))
    else
      render('edit')
    end
  end
# Delete
  def delete
    @section = Section.find(params[:id])
  end

  def destroy
   @section = Section.find(params[:id])
   @section.destroy 
   redirect_to(sections_path)
  end
  private
  def section_params
    params.require(:section).permit(:position, :name, :content_type, :page_id, :visible)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
layout 'admin'
  def new
    @subject = Subject.new
  end

  def create
    # Intanciate new Object
    @subject = Subject.new(subject_params)

    # Save the Object
    if @subject.save 
      flash[:notice]= "Subject Created Successfully"
      redirect_to(subjects_path)
    else
    render('new')
    end
  end

  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
  # Intanciate new Object
    @subject = Subject.find(params[:id])

    # Save the Object
    if @subject.update_attributes(subject_params)
      flash[:notice]= "Subject Updated Successfully"
      redirect_to(subject_path(@subject))
      else
    render('edit')
    end
  end  
  

  def delete
    @subject = Subject.find(params[:id])

  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice]= "#{@subject.name} Deleted Successfully"
    redirect_to(subjects_path)

  end

  private
  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manyusers_helper.rb
module ManyusersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<% @page_title = "Admin Menu" %>

<%= form_for(access_attempt_login_path, :method => :post) do %>
<tr>
    <td> <%= label_tag(:username) %></td>
    <td> <%= text_field_tag(:username, params[:username]) %></td>
</tr>

<tr>
    <td> <%= label_tag(:password) %></td>
    <td> <%= password_field_tag(:password) %></td>
</tr>

<tr>
    <td> <%= submit_tag("Log in") %></td>
</tr>
<% end %>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu" %>

<ul>
    <li><%= link_to("Manage Subjects", subjects_path)  %></li>
    <li></li><%= link_to("Manage Pages", pages_path)  %>
    <li></li><%= link_to("Manage Sections", sections_path)  %>
    <li></li><%= link_to("Manage Admin Users", '#')  %>
    <li></li><%= link_to("Logout",access_logout_path)  %>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple CMS : <%= @page_title || "Admin User" %></title>
</head>
<body>
<%#before layout%>
    <%= yield %>
    <%#after layout%>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/manyusers/delete.html.erb
<h1>Manyusers#delete</h1>
<p>Find me in app/views/manyusers/delete.html.erb</p>

app/views/manyusers/edit.html.erb
<h1>Manyusers#edit</h1>
<p>Find me in app/views/manyusers/edit.html.erb</p>

app/views/manyusers/index.html.erb
<h1>Manyusers#index</h1>
<p>Find me in app/views/manyusers/index.html.erb</p>

app/views/manyusers/show.html.erb
<h1>Manyusers#show</h1>
<p>Find me in app/views/manyusers/show.html.erb</p>

app/views/manyusers/update.html.erb
<h1>Manyusers#update</h1>
<p>Find me in app/views/manyusers/update.html.erb</p>

app/views/pages/_form.html.erb
<table>
<tr>
    <td>Position :<%= f.number_field(:position) %>
</td>
</tr>
    <tr>
        <td>Name :<%= f.text_field(:name) %>
    </td>
    </tr>
    <tr>
        <td>Permalink :<%= f.text_field(:permalink) %>
    </td>
    </tr>
    <tr>
        <td>Visible :<%= f.text_field(:visible) %>
    </td>
    </tr>
    <tr>
        <td>Subject ID :<%= f.text_field(:subject_id) %>
    </td>
    </tr>
</table>
    

app/views/pages/delete.html.erb
<h1>Edit  Page</h1>

<%= form_for(@page, :method => 'delete') do |f| %>
<table>
<tr>
    <td>Position :<%= f.number_field(:position) %>
</td>
</tr>
    <tr>
        <td>Name :<%= f.text_field(:name) %>
    </td>
    </tr>
    <tr>
        <td>Permalink :<%= f.text_field(:permalink) %>
    </td>
    </tr>
    <tr>
        <td>Visible :<%= f.text_field(:visible) %>
    </td>
    </tr>
    <tr>
        <td>Subject ID :<%= f.text_field(:subject_id) %>
    </td>
    </tr>
    <tr>
        <td><%= submit_tag("Delete")%>
    </td>
    </tr>
</table>
<% end %>
 

app/views/pages/edit.html.erb
<h1>Edit  Page</h1>

<%= form_for(@page) do |f| %>

<%= render(:partial => 'form', :locals =>{:f => f}) %>
    
        <%= submit_tag("Edit")%>
<% end %>
 

app/views/pages/index.html.erb
<% @page_title = "All Pages" %>
<h1>All Pages</h1>

<%= link_to("Create New Page",new_page_path)  %>
<tr>
    <td><br/><br/></td>
</tr>

<table>
<tr>
    <td>#</td><td>&#160;&#160;&#160;</td><td>Name</td><td>&#160;&#160;&#160;</td><td>Visible</td><td>&#160;&#160;&#160;</td><td>PermaLink</td>    <td>&#160;&#160;</td>
<td>  Actions</td>
</tr>
<% @pages.each do |page| %>
<tr>
    <td><%= page.position %></td>
    <td>&#160;&#160;&#160;</td>
    <td><%= page.name %></td>
    <td>&#160;&#160;&#160;</td>
    <td><%= page.permalink %></td>
    <td>&#160;&#160;&#160;</td>
    <td><%= page.visible %></td>
    <td>&#160;&#160;</td>
    <td>
    <%= link_to("Show",page_path(page.id))  %>
    <%= link_to("Edit", edit_page_path(page.id))  %>
    <%= link_to("Delete",delete_page_path(page.id))  %>
    </td>
</tr>
<% end %>
</table>

app/views/pages/new.html.erb
<h1>Create New Page</h1>

<%= form_for(@page) do |f| %>


    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <%= submit_tag("Create")%>
<% end %>

 

app/views/pages/show.html.erb
<%= link_to("<< Back to All Pages",pages_path)  %>
<h1>Page </h1>

<table>
<tr>
    <td>Page Position: <%= @page.position %></td>
</tr>
<tr>
    <td>Page Name :<%= @page.name %></td>

</tr>
<tr>
    <td>Permalink: <%= @page.permalink %></td>
</tr>
<tr>
    <td>Visiblity : <%= @page.visible %></td>

</tr>
</tr>
    <td>Creatd at : <%=@page.created_at %></td><td>Updated at : <%=@page.updated_at %></td>
</tr>
</table>

app/views/sections/delete.html.erb
<h1>Sections Deleter</h1>
<%=form_for(@section, :method=>'delete') do |f| %>

<table>

    <tr>
        <td>Position : <%= f.number_field(:position) %>
</td>
    </tr>
    <tr>
        <td>Name: <%= f.text_field(:name) %>
</td>
    </tr>
    <tr>
        <td>visiblity<%= f.text_field(:visible) %>
</td>
    </tr>
    <tr>
        <td>Content type<%= f.text_field(:content_type) %>
</td>
    </tr>
    <tr>
        <td>Page ID<%= f.number_field(:page_id) %>
</td>
    </tr>
    <tr>
        <td><%= submit_tag("Delete") %>
</td>
    </tr>
</table>
    <% end %>

app/views/sections/edit.html.erb
<h1>Sections Edit</h1>
<%=form_for(@section) do |f| %>

<table>

    <tr>
        <td>Position : <%= f.number_field(:position) %>
</td>
    </tr>
    <tr>
        <td>Name: <%= f.text_field(:name) %>
</td>
    </tr>
    <tr>
        <td>visiblity<%= f.text_field(:visible) %>
</td>
    </tr>
    <tr>
        <td>Content type<%= f.text_field(:content_type) %>
</td>
    </tr>
    <tr>
        <td>Page ID<%= f.number_field(:page_id) %>
</td>
    </tr>
    <tr>
        <td><%= submit_tag("Update") %>
</td>
    </tr>
</table>
    <% end %>

app/views/sections/index.html.erb
<%## Table name: sections
#
#  id           :integer          not null, primary key
#  section_id      :integer
#  name         :string
#  position     :integer
#  visible      :boolean          default("false")
#  content_type :string
#  content      :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null%>
<h1>All Sections</h1>
<%= link_to("Create New Section",new_section_path)  %>
<table>
<tr>
    <td>#</td><td>&#160;&#160;&#160;</td><td>Name</td><td>&#160;&#160;&#160;</td><td>Visible</td><td>&#160;&#160;&#160;</td>
    <td>Content Type</td><td>&#160;&#160;&#160;</td><td>Page ID</td><td>&#160;&#160;&#160;</td><td>Action</td>
</tr>


<% @sections.each do |section| %>
<tr>
    <td><%= section.position %></td><td>&#160;&#160;&#160;</td>
    <td><%= section.name %></td><td>&#160;&#160;&#160;</td>
    <td><%= section.visible %></td><td>&#160;&#160;&#160;</td>
    <td><%= section.content_type %></td><td>&#160;&#160;&#160;</td>
    <td><%= section.page_id %></td><td>&#160;&#160;&#160;</td>
    <td>
    <%= link_to("Show",section_path(section.id))  %>
    <%= link_to("Edit",edit_section_path(section.id))  %>
    <%= link_to("Delete",delete_section_path(section.id))  %>
    </td>
</tr>
<% end %>

</table>

app/views/sections/new.html.erb
<h1>Sections new</h1>

<table>
<%=form_for(@section) do |f| %>

    <tr>
        <td>Position : <%= f.number_field(:position) %>
</td>
    </tr>
    <tr>
        <td>Name: <%= f.text_field(:name) %>
</td>
    </tr>
    <tr>
        <td>visiblity<%= f.text_field(:visible) %>
</td>
    </tr>
    <tr>
        <td>Content type<%= f.text_field(:content_type) %>
</td>
    </tr>
    <tr>
        <td>Page ID<%= f.number_field(:page_id) %>
</td>
    </tr>
    <tr>
        <td><%= submit_tag("Create") %>
</td>
    </tr>
    <% end %>
</table>

app/views/sections/show.html.erb
<%= link_to("<<All Sections", sections_path)  %>
<table>
    <tr>
        <td>Position : <%= @section.position %></td><td>&#160;&#160;&#160;</td>
    </tr>
    <tr>
        <td>Name: <%= @section.name %></td><td>&#160;&#160;&#160;</td>
    </tr>
    <tr>
        <td>Visiblity : <%= @section.visible %></td><td>&#160;&#160;&#160;</td>
    </tr>
    <tr>
        <td>Content type : <%= @section.content_type %></td><td>&#160;&#160;&#160;</td>
    </tr>
    <tr>
        <td>Page ID :<%= @section.page_id %></td><td>&#160;&#160;&#160;</td>
    </tr>
    <tr>
        <td>Created At : <%= @section.created_at %></td><td>&#160;&#160;&#160;</td>
        <td>Updated At: <%= @section.updated_at %></td><td>&#160;&#160;&#160;</td>
    </tr>
</table>

app/views/subjects/delete.html.erb
<h1>Subjects edit</h1>

<%= form_for(@subject, :method => 'delete') do |f| %>
<table>
    <tr>
        <td>Name :</td><td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
        <td>Position :</td><td><%= f.number_field(:position) %></td>
    </tr>
    <tr>
        <td>Visible :</td><td><%= f.text_field(:visible) %></td>
    </tr>
    <tr>
    <td><%= submit_tag("Delete Subject") %></td>
    </tr>
</table>
<% end %>

app/views/subjects/edit.html.erb
<h1>Subjects edit</h1>

<%= form_for(@subject) do |f| %>
<table>
    <tr>
        <td>Name :</td><td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
        <td>Position :</td><td><%= f.number_field(:position) %></td>
    </tr>
    <tr>
        <td>Visible :</td><td><%= f.text_field(:visible) %></td>
    </tr>
    <tr>
    <td><%= submit_tag("Update") %></td>
    </tr>
</table>
<% end %>

app/views/subjects/index.html.erb
<% if !flash[:notice].blank? %>
<%= flash[:notice] %>
<% end %>
<h1>Subjects</h1>
<%= link_to("Add new Subject", new_subject_path)  %> <br /><br />

<table>
    <tr>
        <td>#</td><td>&#160;&#160;&#160;&#160;</td><td>&#160;&#160;&#160;&#160;</td><td>Subject</td><td>&#160;&#160;&#160;&#160;</td><td>&#160;&#160;&#160;&#160;</td><td>Visible</td><td>&#160;&#160;&#160;&#160;</td><td>Pages</td><td>&#160;&#160;&#160;&#160;</td><td>Actions</td>
    </tr>
    <% @subjects.each do |subject| %>
        <tr>
            <td><%=subject.position%></td>
            <td>&#160;&#160;&#160;&#160;</td><td>&#160;&#160;&#160;&#160;</td>
            <td><%=subject.name%></td>
            <td>&#160;&#160;&#160;&#160;</td><td>&#160;&#160;&#160;&#160;</td>
            <td><%= subject.visible ? 'Yes' : 'No' %></td>
            <td>&#160;&#160;&#160;&#160;&#160;</td>
            <td><%=subject.pages.size%></td>
            <td>&#160;&#160;&#160;&#160;</td>
            <td>
            <%= link_to("Show", subject_path(subject.id))  %>
            <%= link_to("Edit", edit_subject_path(subject.id))  %>
            <%= link_to("Delete", delete_subject_path(subject.id))  %>
            </td>
        </tr>
    <% end %>
</table>

app/views/subjects/new.html.erb
<h1>Add new Subject</h1>

<%= form_for(@subject, :url => subjects_path, :method => 'post' ) do |f| %>
<table>
    <tr>
        <td>Name :</td><td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
        <td>Position :</td><td><%= f.number_field(:position) %></td>
    </tr>
    <tr>
        <td>Visible :</td><td><%= f.text_field(:visible) %></td>
    </tr>
    <tr>
    <td><%= submit_tag("Create") %></td>
    </tr>
</table>
<% end %>

app/views/subjects/show.html.erb
<% if !flash[:notice].blank? %>
<%= flash[:notice  ] %>
<% end %>
<h1>Edit Subject</h1> 
<%= link_to("All Subjects", subjects_path)  %> <br /><br />

<table>
    <tr>
        <td>Subject Name</td>
    </tr>
    <tr>
        <td><%= @subject.name %></td>
    </tr>
    <tr>
    <td>
    <hr></td>
    </tr>
    <tr colspan="2" >
        <td>Subject Position : <%= @subject.position %></td>
    <td >Subject Visiblity : <%= @subject.visible ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
    <td>
    <hr></td>
    </tr>
    <tr>
    <td>Subject Created At : <%= @subject.created_at %> && Subject Updated at : <%= @subject.updated_at %></td>
    </tr>

</table>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>